const CustomScrollbar = () => {
  return (
    <svg
      width="200"
      height="118"
      viewBox="0 0 200 118"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <rect width="200" height="118" rx="8" fill="var(--color-contrast)"></rect>
      <rect
        x="0.5"
        y="0.5"
        width="199"
        height="117"
        rx="7.5"
        stroke="var(--border-color-default)"
        strokeOpacity="0.6"
      ></rect>
      <rect
        x="9"
        y="14"
        width="109.748"
        height="6"
        rx="2"
        fill="var(--background-color-highlight)"
      ></rect>
      <rect
        x="9"
        y="26"
        width="159"
        height="4"
        rx="2"
        fill="var(--background-color-muted)"
      ></rect>
      <rect
        x="9"
        y="34"
        width="159"
        height="4"
        rx="2"
        fill="var(--background-color-muted)"
      ></rect>
      <rect
        x="9"
        y="42"
        width="95.625"
        height="4"
        rx="2"
        fill="var(--background-color-muted)"
      ></rect>
      <rect
        x="9"
        y="76"
        width="109.748"
        height="6"
        rx="2"
        fill="var(--background-color-highlight)"
      ></rect>
      <rect
        x="9"
        y="88"
        width="159"
        height="4"
        rx="2"
        fill="var(--background-color-muted)"
      ></rect>
      <rect
        x="9"
        y="96"
        width="95.625"
        height="4"
        rx="2"
        fill="var(--background-color-muted)"
      ></rect>
      <rect
        x="192"
        y="5"
        width="5"
        height="108"
        rx="2.5"
        fill="var(--background-color-muted)"
      ></rect>
      <rect
        x="191.5"
        y="44.0684"
        width="6"
        height="29.8633"
        rx="3"
        fill="var(--text-color-muted)"
      ></rect>
    </svg>
  );
};

export default CustomScrollbar;
