export type RegistryEntry = {
  file: string;
};

export const registry: Record<string, RegistryEntry> = {
  "button-default": { file: "buttons/button-default.tsx" },
  "button-variants": { file: "buttons/button-variants.tsx" },
  "button-colors": { file: "buttons/button-colors.tsx" },
  "button-sizes": { file: "buttons/button-sizes.tsx" },
  "button-shapes": { file: "buttons/button-shapes.tsx" },
  "button-with-icon": { file: "buttons/button-with-icon.tsx" },
  "button-icons": { file: "buttons/button-icons.tsx" },
  "button-full-width": { file: "buttons/full-width.tsx" },
  "button-disabled": { file: "buttons/button-disabled.tsx" },
  "accordion-default": { file: "accordion/accordion-default.tsx" },
  "accordion-multiple": { file: "accordion/accordion-multiple.tsx" },
  "accordion-disabled": { file: "accordion/accordion-disabled.tsx" },
  "avatar-default": { file: "avatar/avatar-default.tsx" },
  "avatar-sizes": { file: "avatar/avatar-sizes.tsx" },
  "avatar-status": { file: "avatar/avatar-status.tsx" },
  "avatar-fallback": { file: "avatar/avatar-fallback.tsx" },
  "avatar-group": { file: "avatar/avatar-group.tsx" },
  "alert-default": { file: "alert/alert-default.tsx" },
  "alert-variants": { file: "alert/alert-variants.tsx" },
  "alert-colors": { file: "alert/alert-colors.tsx" },
  "alert-with-icon": { file: "alert/alert-with-icon.tsx" },
  "badge-default": { file: "badge/badge-default.tsx" },
  "badge-variants": { file: "badge/badge-variants.tsx" },
  "badge-colors": { file: "badge/badge-colors.tsx" },
  "badge-sizes": { file: "badge/badge-sizes.tsx" },
  "badge-link": { file: "badge/badge-link.tsx" },
  "badge-with-action": { file: "badge/badge-with-action.tsx" },
  "breadcrumb-default": { file: "breadcrumb/breadcrumb-default.tsx" },
  "breadcrumb-separators": { file: "breadcrumb/breadcrumb-separators.tsx" },
  "button-group-default": { file: "button-group/button-group-default.tsx" },
  "button-group-vertical": { file: "button-group/button-group-vertical.tsx" },
  "button-group-sizes": { file: "button-group/button-group-sizes.tsx" },
  "button-group-toolbar": { file: "button-group/button-group-toolbar.tsx" },
};
