export type RegistryEntry = {
  file: string;
};

export const registry: Record<string, RegistryEntry> = {
  "button-default": { file: "buttons/button-default.tsx" },
  "button-variants": { file: "buttons/button-variants.tsx" },
  "button-colors": { file: "buttons/button-colors.tsx" },
  "button-sizes": { file: "buttons/button-sizes.tsx" },
  "button-shapes": { file: "buttons/button-shapes.tsx" },
  "button-with-icon": { file: "buttons/button-with-icon.tsx" },
  "button-icons": { file: "buttons/button-icons.tsx" },
  "button-full-width": { file: "buttons/full-width.tsx" },
  "button-disabled": { file: "buttons/button-disabled.tsx" },
  "accordion-default": { file: "accordion/accordion-default.tsx" },
  "accordion-multiple": { file: "accordion/accordion-multiple.tsx" },
  "accordion-disabled": { file: "accordion/accordion-disabled.tsx" },
  "avatar-default": { file: "avatar/avatar-default.tsx" },
  "avatar-sizes": { file: "avatar/avatar-sizes.tsx" },
  "avatar-status": { file: "avatar/avatar-status.tsx" },
  "avatar-fallback": { file: "avatar/avatar-fallback.tsx" },
  "avatar-group": { file: "avatar/avatar-group.tsx" },
  "alert-default": { file: "alert/alert-default.tsx" },
  "alert-variants": { file: "alert/alert-variants.tsx" },
  "alert-colors": { file: "alert/alert-colors.tsx" },
  "alert-with-icon": { file: "alert/alert-with-icon.tsx" },
  "badge-default": { file: "badge/badge-default.tsx" },
  "badge-variants": { file: "badge/badge-variants.tsx" },
  "badge-colors": { file: "badge/badge-colors.tsx" },
  "badge-sizes": { file: "badge/badge-sizes.tsx" },
  "badge-link": { file: "badge/badge-link.tsx" },
  "badge-with-action": { file: "badge/badge-with-action.tsx" },
  "breadcrumb-default": { file: "breadcrumb/breadcrumb-default.tsx" },
  "breadcrumb-separators": { file: "breadcrumb/breadcrumb-separators.tsx" },
  "button-group-default": { file: "button-group/button-group-default.tsx" },
  "button-group-vertical": { file: "button-group/button-group-vertical.tsx" },
  "button-group-sizes": { file: "button-group/button-group-sizes.tsx" },
  "button-group-toolbar": { file: "button-group/button-group-toolbar.tsx" },
  "form-control-default": { file: "form-control/form-control-default.tsx" },
  "form-control-variants": { file: "form-control/form-control-variants.tsx" },
  "form-control-sizes": { file: "form-control/form-control-sizes.tsx" },
  "form-control-colors": { file: "form-control/form-control-colors.tsx" },
  "form-control-validation": {
    file: "form-control/form-control-validation.tsx",
  },
  "form-control-textarea": { file: "form-control/form-control-textarea.tsx" },
  "form-control-with-label": {
    file: "form-control/form-control-with-label.tsx",
  },
  "form-control-with-icon": { file: "form-control/form-control-with-icon.tsx" },
  "form-control-disabled": { file: "form-control/form-control-disabled.tsx" },
  "select-default": { file: "select/select-default.tsx" },
  "select-variants": { file: "select/select-variants.tsx" },
  "select-sizes": { file: "select/select-sizes.tsx" },
  "select-colors": { file: "select/select-colors.tsx" },
  "select-validation": { file: "select/select-validation.tsx" },
  "select-disabled": { file: "select/select-disabled.tsx" },
  "checkbox-default": { file: "checkbox/checkbox-default.tsx" },
  "checkbox-colors": { file: "checkbox/checkbox-colors.tsx" },
  "checkbox-sizes": { file: "checkbox/checkbox-sizes.tsx" },
  "checkbox-inline": { file: "checkbox/checkbox-inline.tsx" },
  "checkbox-indeterminate": { file: "checkbox/checkbox-indeterminate.tsx" },
  "checkbox-disabled": { file: "checkbox/checkbox-disabled.tsx" },
  "radio-default": { file: "radio/radio-default.tsx" },
  "radio-colors": { file: "radio/radio-colors.tsx" },
  "radio-sizes": { file: "radio/radio-sizes.tsx" },
  "radio-inline": { file: "radio/radio-inline.tsx" },
  "radio-disabled": { file: "radio/radio-disabled.tsx" },
  "switch-default": { file: "switch/switch-default.tsx" },
  "switch-colors": { file: "switch/switch-colors.tsx" },
  "switch-sizes": { file: "switch/switch-sizes.tsx" },
  "switch-inline": { file: "switch/switch-inline.tsx" },
  "switch-disabled": { file: "switch/switch-disabled.tsx" },
  "input-group-default": { file: "input-group/input-group-default.tsx" },
  "input-group-sizes": { file: "input-group/input-group-sizes.tsx" },
  "input-group-button": { file: "input-group/input-group-button.tsx" },
  "input-group-multiple": { file: "input-group/input-group-multiple.tsx" },
  "floating-label-default": {
    file: "floating-label/floating-label-default.tsx",
  },
  "floating-label-textarea": {
    file: "floating-label/floating-label-textarea.tsx",
  },
  "floating-label-select": { file: "floating-label/floating-label-select.tsx" },
  "form-range-default": { file: "form-range/form-range-default.tsx" },
  "form-range-sizes": { file: "form-range/form-range-sizes.tsx" },
  "form-range-colors": { file: "form-range/form-range-colors.tsx" },
  "form-range-disabled": { file: "form-range/form-range-disabled.tsx" },
  "card-default": { file: "card/card-default.tsx" },
  "card-header-footer": { file: "card/card-header-footer.tsx" },
  "card-image": { file: "card/card-image.tsx" },
  "card-image-overlay": { file: "card/card-image-overlay.tsx" },
  "card-aside": { file: "card/card-aside.tsx" },
  "card-action": { file: "card/card-action.tsx" },
  "card-group": { file: "card/card-group.tsx" },
  "close-button-default": { file: "close-button/close-button-default.tsx" },
  "close-button-variants": { file: "close-button/close-button-variants.tsx" },
  "close-button-shapes": { file: "close-button/close-button-shapes.tsx" },
  "close-button-disabled": { file: "close-button/close-button-disabled.tsx" },
  "list-group-default": { file: "list-group/list-group-default.tsx" },
  "list-group-active-disabled": {
    file: "list-group/list-group-active-disabled.tsx",
  },
  "list-group-action": { file: "list-group/list-group-action.tsx" },
  "list-group-numbered": { file: "list-group/list-group-numbered.tsx" },
  "list-group-pinned": { file: "list-group/list-group-pinned.tsx" },
  "list-group-custom-content": {
    file: "list-group/list-group-custom-content.tsx",
  },
  "nav-default": { file: "nav/nav-default.tsx" },
  "nav-tabs": { file: "nav/nav-tabs.tsx" },
  "nav-underline": { file: "nav/nav-underline.tsx" },
  "nav-colors": { file: "nav/nav-colors.tsx" },
  "nav-active": { file: "nav/nav-active.tsx" },
  "nav-disabled": { file: "nav/nav-disabled.tsx" },
  "navbar-default": { file: "navbar/navbar-default.tsx" },
  "navbar-expand": { file: "navbar/navbar-expand.tsx" },
  "navbar-collapse": { file: "navbar/navbar-collapse.tsx" },
  "navbar-always-collapsed": { file: "navbar/navbar-always-collapsed.tsx" },
  "navbar-scrollable": { file: "navbar/navbar-scrollable.tsx" },
  "navbar-text": { file: "navbar/navbar-text.tsx" },
  "navbar-custom-toggle": { file: "navbar/navbar-custom-toggle.tsx" },
  "pagination-default": { file: "pagination/pagination-default.tsx" },
  "pagination-sizes": { file: "pagination/pagination-sizes.tsx" },
  "pagination-circle": { file: "pagination/pagination-circle.tsx" },
  "pagination-variants": { file: "pagination/pagination-variants.tsx" },
  "pagination-colors": { file: "pagination/pagination-colors.tsx" },
  "pagination-disabled": { file: "pagination/pagination-disabled.tsx" },
  "table-default": { file: "table/table-default.tsx" },
  "table-striped": { file: "table/table-striped.tsx" },
  "table-striped-columns": { file: "table/table-striped-columns.tsx" },
  "table-hover": { file: "table/table-hover.tsx" },
  "table-bordered": { file: "table/table-bordered.tsx" },
  "table-borderless": { file: "table/table-borderless.tsx" },
  "table-sizes": { file: "table/table-sizes.tsx" },
  "table-colors": { file: "table/table-colors.tsx" },
  "table-active": { file: "table/table-active.tsx" },
  "table-highlight": { file: "table/table-highlight.tsx" },
  "table-sticky-header": { file: "table/table-sticky-header.tsx" },
  "table-caption": { file: "table/table-caption.tsx" },
  "table-footer": { file: "table/table-footer.tsx" },
  "collapsible-default": { file: "collapsible/collapsible-default.tsx" },
  "collapsible-default-open": {
    file: "collapsible/collapsible-default-open.tsx",
  },
  "collapsible-controlled": { file: "collapsible/collapsible-controlled.tsx" },
  "collapsible-disabled": { file: "collapsible/collapsible-disabled.tsx" },
  "dialog-default": { file: "dialog/dialog-default.tsx" },
  "dialog-centered": { file: "dialog/dialog-centered.tsx" },
  "dialog-sizes": { file: "dialog/dialog-sizes.tsx" },
  "dialog-scrollable": { file: "dialog/dialog-scrollable.tsx" },
  "dialog-fullscreen": { file: "dialog/dialog-fullscreen.tsx" },
  "dialog-controlled": { file: "dialog/dialog-controlled.tsx" },
  "drawer-default": { file: "drawer/drawer-default.tsx" },
  "drawer-direction": { file: "drawer/drawer-direction.tsx" },
  "drawer-without-overlay": { file: "drawer/drawer-without-overlay.tsx" },
  "drawer-scrollable": { file: "drawer/drawer-scrollable.tsx" },
  "dropdown-default": { file: "dropdown/dropdown-default.tsx" },
  "dropdown-groups": { file: "dropdown/dropdown-groups.tsx" },
  "dropdown-placement": { file: "dropdown/dropdown-placement.tsx" },
  "dropdown-disabled": { file: "dropdown/dropdown-disabled.tsx" },
  "dropdown-item-text": { file: "dropdown/dropdown-item-text.tsx" },
  "popover-default": { file: "popover/popover-default.tsx" },
  "popover-placement": { file: "popover/popover-placement.tsx" },
  "popover-with-close": { file: "popover/popover-with-close.tsx" },
  "popover-controlled": { file: "popover/popover-controlled.tsx" },
  "tabs-default": { file: "tabs/tabs-default.tsx" },
  "tabs-underline": { file: "tabs/tabs-underline.tsx" },
  "tabs-plain": { file: "tabs/tabs-plain.tsx" },
  "tabs-colors": { file: "tabs/tabs-colors.tsx" },
  "tabs-disabled": { file: "tabs/tabs-disabled.tsx" },
  "tooltip-default": { file: "tooltip/tooltip-default.tsx" },
  "tooltip-placement": { file: "tooltip/tooltip-placement.tsx" },
  "tooltip-delay": { file: "tooltip/tooltip-delay.tsx" },
  "tooltip-provider": { file: "tooltip/tooltip-provider.tsx" },
  "grid-basic": { file: "grid/basic.tsx" },
  "grid-equal-width": { file: "grid/equal-width.tsx" },
  "grid-variable-width": { file: "grid/variable-width.tsx" },
  "grid-all-breakpoints": { file: "grid/all-breakpoints.tsx" },
  "grid-mix-match": { file: "grid/mix-match.tsx" },
  "grid-row-cols": { file: "grid/row-cols.tsx" },
  "grid-row-cols-auto": { file: "grid/row-cols-auto.tsx" },
  "grid-row-cols-responsive": { file: "grid/row-cols-responsive.tsx" },
  "grid-nesting": { file: "grid/nesting.tsx" },
  "grid-align-vertical": { file: "grid/align-vertical.tsx" },
  "grid-align-self": { file: "grid/align-self.tsx" },
  "grid-align-horizontal": { file: "grid/align-horizontal.tsx" },
  "grid-order": { file: "grid/order.tsx" },
  "grid-offset": { file: "grid/offset.tsx" },
  "grid-gutters-horizontal": { file: "grid/gutters-horizontal.tsx" },
  "grid-gutters-vertical": { file: "grid/gutters-vertical.tsx" },
  "grid-gutters": { file: "grid/gutters.tsx" },
  "grid-row-cols-gutters": { file: "grid/row-cols-gutters.tsx" },
  "grid-no-gutters": { file: "grid/no-gutters.tsx" },
  "reboot-headings": { file: "reboot/headings.tsx" },
  "reboot-paragraph": { file: "reboot/paragraph.tsx" },
  "reboot-links": { file: "reboot/links.tsx" },
  "reboot-buttons": { file: "reboot/buttons.tsx" },
  "reboot-horizontal-rules": { file: "reboot/horizontal-rules.tsx" },
  "reboot-lists": { file: "reboot/lists.tsx" },
  "reboot-description-lists": { file: "reboot/description-lists.tsx" },
  "reboot-inline-code": { file: "reboot/inline-code.tsx" },
  "reboot-address": { file: "reboot/address.tsx" },
  "reboot-blockquote": { file: "reboot/blockquote.tsx" },
  "reboot-legend": { file: "reboot/legend.tsx" },
  "reboot-captions": { file: "reboot/captions.tsx" },
};
